Sprint 3
Sensi44/Messenger pull request #4
Opened 2024-10-26 14:15 UTC by Sensi44

2024-10-27 19:31 UTC, aromanovnik requested changes
Добрый день, Евгений!

Работа выполнена очень хорошо: настроен роутинг, API функционирует корректно, активна только одна страница в DOM, а после обновления отображается та же страница, что делает навигацию более плавной. Код выглядит чисто и аккуратно.

Тем не менее, есть несколько замечаний, которые потребуют доработки. Более подробно о них написано в комментариях к коду.

**Что нужно исправить**:
* По заданию страницы приложения должны открываться по следующим маршрутам: `/` (страница входа), `/sign-up` (страница регистрации), `/settings` (страница настроек пользователя ), `/messenger` (чат).
* Если пользователь уже авторизован, необходимо настроить редирект со страниц `/` и `/sign-up` на `/messenger`, чтобы исключить возможность повторного доступа к страницам регистрации и входа.
* В приложении необходимо проверять авторизацию. Без авторизационной куки пользователю не должно быть доступно открытие чатов.
* Для любых запросов к серверу необходимо в конце цепочки промисов добавлять обработку ошибок с помощью метода `.catch()` или добавить блок `try/catch`. 
* Нужно выводить актуальную информацию об активном чате.

**Что можно улучшить**:
* При удалении или добавлении пользователя из чата было бы удобнее показывать список участников, чтобы сразу выбрать нужного, вместо того чтобы вспоминать его логин или id.
* Закомментированный код лучше не оставлять в проекте, так как вся история изменений сохраняется в Git. В любой момент можно вернуться к предыдущим версиям и посмотреть старый код.
* В проекте **14** `any`, было бы супер уменьшить их количество, например, прописав конкретные типы, использовать дженерики или, в крайнем случае, заменить на unknown. Это улучшит типизацию и сделает код более предсказуемым и безопасным.
* При запуске команды npm i обнаружены 8 уязвимостей. Их лучше устранить, выполнив команду npm audit fix. Это поможет сделать проект более безопасным.
* При запуске команды `npm run lint` обнаружено 20 проблем, которые лучше решить для соблюдения стандартов кодирования и улучшения качества кода.

Напоминаю, что работа может быть принята только после исправления всех критических замечаний **Надо исправить**.

Удачного рефакторинга кода.

2024-10-27 19:31 UTC, aromanovnik commented on src/components/chatWindow/chatWindow.ts
> +    // console.log('chatWindow - messages', this.props.messages);
**Можно лучше**: Закомментированный код лучше не оставлять в проекте, так как вся история изменений сохраняется в Git. В любой момент можно вернуться к предыдущим версиям и посмотреть старый код. Оставление закомментированных участков засоряет кодовую базу и снижает её читаемость.

2024-10-27 19:31 UTC, aromanovnik commented on src/components/chatWindow/chatWindow.ts
>            {{{ chatWindowNav }}}
**Надо исправить**: Нужно выводить актуальную информацию об активном чате.

<img width="696" alt="Снимок экрана 2024-10-27 в 21 38 51" src="https://github.com/user-attachments/assets/3e20364c-e31b-4d3a-b33f-266c7d8dbe9e">

2024-10-27 19:31 UTC, aromanovnik commented on src/main.ts
> +  .use('/', Pages.NavigatePage)
**Надо исправить**: По заданию страницы приложения должны открываться по следующим маршрутам: `/` (страница входа), `/sign-up` (страница регистрации), `/settings` (страница настроек пользователя ), `/messenger` (чат).

2024-10-27 19:31 UTC, aromanovnik commented on src/main.ts
> +  .use('/signInPage', Pages.SignInPage)
**Надо исправить**: Если пользователь уже авторизован, необходимо настроить редирект со страниц `/` и `/sign-up` на `/messenger`, чтобы исключить возможность повторного доступа к страницам регистрации и входа.

<img width="1204" alt="Снимок экрана 2024-10-27 в 21 56 55" src="https://github.com/user-attachments/assets/ee9faff2-3352-4b61-be81-e076f6a80d92">

2024-10-27 19:31 UTC, aromanovnik commented on src/components/addDeleteUserModal/addDeleteUserModal.ts
>            {{#Typography style="text-l"}}Добавить пользователя{{/Typography}}
**Можно лучше**: При удалении или добавлении пользователя из чата было бы удобнее показывать список участников, чтобы сразу выбрать нужного, вместо того чтобы вспоминать его логин или id.

2024-10-27 19:31 UTC, aromanovnik commented on src/components/addDeleteUserModal/addDeleteUserModal.ts
> +    const usersArray = await searchUser(this.userName);
**Надо исправить**: Для любых запросов к серверу необходимо в конце цепочки промисов добавлять обработку ошибок с помощью метода `.catch()` или добавить блок `try/catch`. Это важно для предотвращения неожиданных сбоев в приложении и корректной обработки ошибок. Нужно исправить это везде, где происходят запросы к серверу.

2024-10-27 19:31 UTC, aromanovnik commented on src/main.ts
> +  .use('/messengerPage', Pages.MessengerPage)
**Надо исправить**: В приложении необходимо проверять авторизацию. Без авторизационной куки пользователю не должно быть доступно открытие чатов. Требуется настроить соответствующие проверки и редиректы на страницу авторизации, если кука отсутствует.

<img width="1135" alt="Снимок экрана 2024-10-27 в 22 14 40" src="https://github.com/user-attachments/assets/3ed04bf0-208a-4933-b32d-aa8703ccdfd5">

2024-10-27 20:34 UTC, Sensi44 commented on src/components/addDeleteUserModal/addDeleteUserModal.ts
>            {{#Typography style="text-l"}}Добавить пользователя{{/Typography}}
на следующем спринте сделаю, 
добавил себе в todo
уже просто глаза текут от этого мессенджера

2024-10-27 20:45 UTC, Sensi44 commented on src/components/addDeleteUserModal/addDeleteUserModal.ts
> +    const usersArray = await searchUser(this.userName);
Согласен, проверил действительно падает с ошибками, исправил

2024-10-27 20:47 UTC, Sensi44 commented
Вроде бы всё исправил
что-то вынес себе в тудушки
ошибки нпм + линтинга поправил, всё по нулям

2024-10-28 08:44 UTC, aromanovnik approved these changes
Поздравляю! Ваша работа принята. Все недочеты исправлены. Желаю успехов в дальнейшей учебе!

2024-10-28 09:32 UTC, merged